[package]
name = "dioxus-components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.5" }
manganis = "0.2.2"

[dev-dependencies]
dioxus = { version = "0.5", features = ["desktop"] }


[features]
