[workspace]
resolver = "3"
members = ["primitives", "preview"]

[workspace.dependencies]
primitives = { path = "primitives" }

# dioxus = { path = "../dioxus/packages/dioxus" }
# dioxus-lib = { path = "../dioxus/packages/dioxus-lib" }
dioxus = "0.6"
dioxus-lib = "0.6"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
