[package]
name = "preview"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"]}
dioxus-primitives.workspace = true
syntect-html = { git = "https://github.com/DioxusLabs/docsite" }

[features]
web = ["dioxus/web"]
server = ["dioxus/server"]
