[package]
name = "preview"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"]}
dioxus-primitives.workspace = true
tracing.workspace = true

[build-dependencies]
syntect = "5.0"

[features]
web = ["dioxus/web"]
server = ["dioxus/server"]
